#!/bin/sh

[ -c /dev/fb0 ] || exit 0

[ -f /etc/splash.ppm ] || exit 0

[ -f /etc/vgamode ] || exit 0

VGAMODE=`cat /etc/vgamode`

case "$1" in
     start)
	# Show splash screen
	fbset ${VGAMODE}
	fbsplash -s /etc/splash.ppm
	;;
     stop)
	# Shut down screen?
	;;
esac
