#!/bin/sh

[ -c /dev/fb0 ] || exit 0

[ -f /etc/splash.ppm ] || exit 0

if test -f /etc/vgamode ; then
    VGAMODE=`cat /etc/vgamode`
fi

case "$1" in
    start)
	# Show splash screen
	if ! test -z "${VGAMODE}" ; then
	    fbset ${VGAMODE}
	fi
	fbsplash -s /etc/splash.ppm
	;;
    stop)
	# Shut down screen?
	;;
esac
